In [1]:
import yfinance as yf
def get_stockmarket():
    try:
        data = yf.Ticker("^GSPC").history(period = '1mo')
        return data
    except Exception as e:
        print(f"Error getting stock market data: {e}")
        return None

In [2]:
raw_sm = get_stockmarket()
raw_sm

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-09-02 00:00:00-04:00,6401.509766,6416.540039,6360.580078,6415.540039,4784000000,0.0,0.0
2025-09-03 00:00:00-04:00,6445.819824,6453.669922,6416.169922,6448.259766,4465360000,0.0,0.0
2025-09-04 00:00:00-04:00,6456.600098,6502.540039,6445.979980,6502.080078,4670770000,0.0,0.0
2025-09-05 00:00:00-04:00,6529.080078,6532.649902,6443.979980,6481.500000,5066120000,0.0,0.0
2025-09-08 00:00:00-04:00,6498.089844,6508.669922,6483.290039,6495.149902,5211500000,0.0,0.0
2025-09-09 00:00:00-04:00,6503.330078,6518.229980,6483.080078,6512.609863,4798350000,0.0,0.0
2025-09-10 00:00:00-04:00,6550.290039,6555.970215,6516.339844,6532.040039,5253010000,0.0,0.0
2025-09-11 00:00:00-04:00,6554.410156,6592.890137,6545.799805,6587.470215,5426460000,0.0,0.0
2025-09-12 00:00:00-04:00,6590.660156,6600.209961,6579.490234,6584.290039,4641640000,0.0,0.0
2025-09-15 00:00:00-04:00,6603.490234,6619.620117,6602.069824,6615.279785,5045020000,0.0,0.0
2025-09-16 00:00:00-04:00,6624.129883,6626.990234,6600.109863,6606.759766,5359510000,0.0,0.0
2025-09-17 00:00:00-04:00,6604.870117,6624.390137,6551.149902,6600.350098,5805340000,0.0,0.0
2025-09-18 00:00:00-04:00,6626.850098,6656.799805,6611.890137,6631.959961,5292400000,0.0,0.0
2025-09-19 00:00:00-04:00,6647.109863,6671.819824,6630.310059,6664.359863,9125960000,0.0,0.0
2025-09-22 00:00:00-04:00,6654.279785,6698.879883,6648.069824,6693.750000,5642620000,0.0,0.0
2025-09-23 00:00:00-04:00,6692.439941,6699.520020,6645.580078,6656.919922,5633620000,0.0,0.0
2025-09-24 00:00:00-04:00,6669.790039,6672.660156,6621.759766,6637.970215,5459180000,0.0,0.0
2025-09-25 00:00:00-04:00,6608.189941,6619.000000,6569.220215,6604.720215,5874670000,0.0,0.0
2025-09-26 00:00:00-04:00,6615.379883,6648.970215,6604.430176,6643.700195,5103110000,0.0,0.0
2025-09-29 00:00:00-04:00,6661.580078,6677.310059,6644.490234,6661.209961,5358760000,0.0,0.0
2025-09-30 00:00:00-04:00,6656.189941,6691.250000,6641.000000,6688.459961,6057210000,0.0,0.0
2025-10-01 00:00:00-04:00,6664.919922,6718.479980,6656.200195,6711.200195,6037950000,0.0,0.0

In [6]:
import pandas as pd
from datetime import datetime

def clean_stockmarket(data):
    if data.empty:
        print("No stock market data to clean")
        return None
    try:
        df = data.reset_index()[['Date', 'Close']].copy()
        df = df.rename(columns={'Date': 'date', 'Close': 'stockmarket_value'})
        df['date'] = df['date'].dt.date
        return df
    except Exception as e:
        print(f"Error cleaning stock market data: {e}")
        return None

In [8]:
stockmarket_data = clean_stockmarket(raw_sm)
stockmarket_data

          date  stockmarket_value
0   2025-09-02        6415.540039
1   2025-09-03        6448.259766
2   2025-09-04        6502.080078
3   2025-09-05        6481.500000
4   2025-09-08        6495.149902
5   2025-09-09        6512.609863
6   2025-09-10        6532.040039
7   2025-09-11        6587.470215
8   2025-09-12        6584.290039
9   2025-09-15        6615.279785
10  2025-09-16        6606.759766
11  2025-09-17        6600.350098
12  2025-09-18        6631.959961
13  2025-09-19        6664.359863
14  2025-09-22        6693.750000
15  2025-09-23        6656.919922
16  2025-09-24        6637.970215
17  2025-09-25        6604.720215
18  2025-09-26        6643.700195
19  2025-09-29        6661.209961
20  2025-09-30        6688.459961
21  2025-10-01        6711.200195

In [24]:
def figure_stockmarket(data):
    if data.empty:
        print("Error estimating stock market trend")
        return None
    try:
        return "Rising" if data.iloc[-1, 1] > data.iloc[0, 1] else "Falling"
    except Exception as e:
        print(f"Error estimating stock market trend: {e}")

In [33]:
from datetime import datetime
stockmarket_estimate = figure_stockmarket(stockmarket_data)
date = datetime.now().date()
stockmarket = pd.DataFrame({'date': [date], 'stockmarket': [stockmarket_estimate]})
stockmarket

         date stockmarket
0  2025-10-02      Rising